### ISSUE TITLE
missing ycast.py file noob question

### ISSUE THREAD

**Issue by zofman** [milaq/YCast#22]
As a Python noob and yamaha receiver owner, i try to understand your ycast server.
I am missing the file ycast.py 
Am i doing something wrong?
Zofman

**Comment by emtee-bc** [comment]
@zofman, I believe @milaq has substantially changed the YCast code and the way it integrates into onto server. The last instance of ycast.py appears to be with the Jun 26, 2019 code commit, 4927524.
Since that commit there has been a big shift in the structure of the code and the way it integrates into server.
Hope this helps.

Mark

**Comment by milaq** [comment]
Please have a look at the readme. It's all in there:

> You can run YCast by using the built-in development server of Flask (not recommended for production use, but should™ be enough for your private home use): python -m ycast

You may run this command from the YCast directory or (if you installed the package via pip) systemwide.

Since there are many questions popping up lately on how to run YCast, maybe I should ship a startscript with the Python package.
I'll have a look at that.

Cheers

**Comment by zofman** [comment]
Thank you milaq for your comment and the lovely, much needed programm!
An installationscript will be much appriciated, especially for those unfamiliar with python! A lot of people have been affected by the policy of both vtuner and yamaha!
Keep up the good work!
