### ISSUE TITLE
Avoid ipv6 localhost attempt

### ISSUE THREAD

**Issue by llagendijk** [milaq/YCast#27]
I started looking at ycast this week, it is great.

I am using ycast with nginx on a virtual machine.
While trying to get it to work I noticed some errors in the NGINX error log related to IPv6 localhost connection. 
As ycast only seems to support ipv4 I changed the nginx config file and replaced the localhost in the proxy_pass to
proxy_pass http://127.0.0.1:8010;

This avoids the (harmless) IPv6 attempts. It may be appropriate to change the sample configuration?

**Comment by milaq** [comment]
Sorry for the late reply and thanks for pointing this one out.

You're right, we are only listening on IPv4 addresses with `listen 80;` and should correctly `proxy_pass` to `127.0.0.1` only.

See https://github.com/milaq/YCast/commit/b89ac21546c16c4fa374533dc7943c31e08a7a7d

I didn't notice this in the first place because the machine I've been running the tests on doesn't use a IPv6 stack.
